ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'USER_DEACTIVATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'INFO_POST_EDITED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'INFO_POST_DELETED';
